import "@repo/ui/styles/globals.css";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { cn } from "@repo/ui/lib/utils";
import { TooltipProvider } from "@repo/ui/components/tooltip";
import { SidebarInset, SidebarProvider } from "@repo/ui/components/sidebar";
import { AppSidebar } from "@/components/app-sidebar";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

const montserrat = Montserrat({ subsets: ["latin"], variable: "--font-sans" });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn("h-full", "antialiased", "font-sans", montserrat.variable)}
    >
      <body>
        <TooltipProvider>
          <SidebarProvider>
            <AppSidebar />
            <SidebarInset>
              <header className="flex items-center justify-between h-16 px-4 shrink-0 border-b"></header>
              <main className="flex-1 overflow-auto p-4">{children}</main>
            </SidebarInset>
          </SidebarProvider>
        </TooltipProvider>
      </body>
    </html>
  );
}
